### PR TITLE
Add Discord Rich Presence support.

### PR DESCRIPTION
**Pull request by NotZoeyDev**
This PR adds support to display Intiface Central's status through Discord Rich Presence (via its IPC api).

This also adds a setting for it which is disabled by default.
It's also only available on desktop but is fully cross-platform, tested on Windows and Linux (macOS implementation is the same as far as I know).

Could easily be improved, honestly, I have never touched Bloc/Cubit before this and I'm pretty sure this could have been implemented in a better way than this.

This also uses a new environment variable named "DISCORD_CLIENT_ID" which should match a client_id provided by a Discord application.

image

### CODE REVIEW

**Comment by qdot** [comment]
@NotZoeyDev Merged it, but I'm not getting anything in the DISCORD_CLIENT_ID env var, and there's no error checking in this, so I'm probably gonna back the patch out. 

Is there something else that needs to happen?

**Comment by NotZoeyDev** [comment]
@qdot Oh right, you'll need to create your own Discord "Application" so you can get your own Discord client ID specifically for Intiface Central. You can create/manage them [here.](https://discord.com/developers/applications)

I did create one temporarily for testing purposes but I figured it'd make more sense to let you create your own so you'd have full control over its information and settings rather than provide one created by me.

I can add error handling to check if the DISCORD_CLIENT_ID variable is set if needed as well so it doesn't error out or anything.

**Comment by qdot** [comment]
Oh! Got it, totally makes sense. I'll convert that to a dart define, that's the same way I bring in my sentry key.

**Comment by NotZoeyDev** [comment]
Sounds good then, should I re-open a new PR with slightly updated code that will check if the environment variable is defined before initializing the Discord's cubit and do anything related to it?

**Comment by qdot** [comment]
Nah, don't worry about it, I'll just merge your stuff on a branch and handle it.

**Comment by NotZoeyDev** [comment]
Awesome, if you have any questions, feel free to hit me up whenever.

**Pull request merged**
